alert('Lets do Nummers!');
var num = prompt('Pick a number');
var num = parseFloat(num);
var numTwo = prompt('Pick another one');
var num = parseFloat(num);
var numTwo = parseFloat(numTwo);
var add = num + numTwo;
var Mult = num * numTwo;
var subtract = num - numTwo;
var divide = num/numTwo;
var message = ' Doing nummers ' + num + ' and ' + numTwo;
var addition = num + ' ';
var additiontwo = numTwo + ' ';
addition += ' + ' + additiontwo + '= ';
var sub = num + ' ';
var subTwo = numTwo + ' ';
sub+= ' - ' + subTwo + ' = ';
var multiplication = num + ' ';
var multiplicationTwo = numTwo + ' ';
multiplication+= ' * ' + multiplicationTwo + ' = ';
var div = num + ' ';
var divTwo = numTwo + ' ';
div+= ' / ' + divTwo + ' = ';
document.write('<h1>'+message+'</h1>');
document.write(addition + add);
document.write("<br>");
document.write(sub + subtract);
document.write("<br>");
document.write(multiplication + Mult);
document.write("<br>");
document.write(div + divide);
